### ISSUE TITLE
Windows = BeautifulSoup4 Not Found!

### ISSUE THREAD

**Issue by Omniferum** [juancarlospaco/css-html-prettify#2]
``` python
BeautifulSoup4 Not Found!, use:  sudo apt-get install python3-bs4
Traceback (most recent call last):
  File "css-html-prettify.py", line 354, in <module>
    orig_prettify = BeautifulSoup.prettify
NameError: name 'BeautifulSoup' is not defined
```

**Comment by ghost** [comment]
```
BeautifulSoup4 Not Found!, use:  sudo apt-get install python3-bs4
```

Then:

`sudo apt-get install python3-bs4` on Linux.
`pip install beautifulsoup4` on Windows _(?)_

It depends on BeautifulSoup4,needs BeautifulSoup4 to work _(thats why is separated from the Minifier)_.
This one has Dependencies.

**Comment by Omniferum** [comment]
I didn't check the requisites section, I only read the first line: StandAlone Async single-file cross-platform Unicode-ready Python3-ready Prettifier Beautifier for the Web.

So I just assumed it to be like the other script.
